---
# https://gist.github.com/atinfinity/aa0d4efb98837abd39bb
- name: dl opencv source
  get_url:
    url: https://github.com/opencv/opencv/archive/3.2.0.tar.gz
    dest: "{{ source_dir }}/opencv-3.2.0.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/opencv-3.2.0.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true


- name: opencv build dir
  file:
    dest: "{{ source_dir }}/opencv-3.2.0/build"
    state: directory
    mode: 0755

- name: dl opencv source
  get_url:
    url: https://github.com/opencv/opencv_contrib/archive/3.2.0.tar.gz
    dest: "{{ source_dir }}/opencv_contrib-3.2.0.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/opencv_contrib-3.2.0.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: opencv_3rdparty source
  git:
    repo: 'git://github.com/opencv/opencv_3rdparty.git'
    dest: "{{ source_dir }}/opencv_3rdparty/"
    depth: 1
    version: ippicv/master_20170418

- name: tar 
  unarchive:
    src: "{{ source_dir }}/opencv_3rdparty/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: opencv build
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/opencv-3.2.0/"
  with_items:
    - "cmake -D CMAKE_INSTALL_PREFIX={{ bin_dir }} -DBUILD_SHARED_LIBS=ON -D OPENCV_EXTRA_MODULES_PATH={{ source_dir }}/opencv_contrib-3.2.0/modules -DBUILD_DOCS=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=RELEASE -DWITH_TBB=ON -DWITH_GTK=ON -DWITH_OPENGL=ON -DWITH_QT=ON -DINSTALL_C_EXAMPLES=ON -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_OPENNI=ON -DWITH_UNICAP=ON -DWITH_V4L=ON -DWITH_XINE=ON -DWITH_OPENEXR=ON -DBUILD_OPENEXR=ON {{ source_dir }}/opencv-3.2.0/"
    - make
    - make install

