---
# http://qiita.com/twaka/items/7555785aea11879d6718
# http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html
# https://github.com/ozzyjohnson/ansible-ffmpeg-build/blob/master/build-ffmpeg.yml
# http://a98.jugem.jp/?eid=419
# tasks for opencv required packages
- name: be sure opencv is insatlled
  yum: name={{ item }} state=latest
  with_items:
    - cmake
    - git
    - gcc
    - gcc-c++
    - python
    - python-devel.x86_64
    - gtk2-devel.x86_64
    - libjpeg-devel
    - libtiff-devel
    - libpng-devel
    - jasper-devel
    - zlib-devel
    - qt4-devel
    - qv4l2 
    - v4l-utils-devel-tools
    - gstreamer-devel
    - libdc1394-devel
    - libv4l
    - totem
    - unicap-devel
    - autoconf

- name: ffmpeg
  yum: name={{ item }} state=latest
  with_items:
    - automake
    - bzip2
    - freetype-devel
    - libtool
    - mercurial
    - nasm
    - pkgconfig
    - zlib-devel

# Download

- name: Download file and force basic auth
  get_url:
    url: http://www.nasm.us/pub/nasm/releasebuilds/2.13.01/nasm-2.13.01.tar.gz
    dest: "{{ source_dir }}/nasm-2.13.01.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/nasm-2.13.01.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: yasm source
  git:
    repo: 'git://github.com/yasm/yasm.git'
    dest: "{{ source_dir }}/yasm/"
    update: no
    accept_hostkey: yes

- name: libx264 source
  git:
    repo: 'git://git.videolan.org/x264'
    dest: "{{ source_dir }}/x264/"
    update: no 

- name: libfdk_aac source
  git:
    repo: 'git://git.code.sf.net/p/opencore-amr/fdk-aac'
    dest: "{{ source_dir }}/fdk-aac/"
    update: no 

- name: Download file and force basic auth
  get_url:
    url: http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
    dest: "{{ source_dir }}/lame-3.99.5.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/lame-3.99.5.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: libopus source
  git:
    repo: 'git://git.opus-codec.org/opus.git'
    dest: "{{ source_dir }}/opus/"
    update: no 

- name: Download file and force basic auth
  get_url:
    url: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
    dest: "{{ source_dir }}/libogg-1.3.2.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/libogg-1.3.2.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true


- name: Download file and force basic auth
  get_url:
    url: http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.4.tar.gz
    dest: "{{ source_dir }}/libvorbis-1.3.4.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/libvorbis-1.3.4.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: libvpx source
  git:
    repo: 'https://chromium.googlesource.com/webm/libvpx.git'
    dest: "{{ source_dir }}/libvpx/"
    update: no 

- name: Download file and force basic auth
  get_url:
    url: http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz
    dest: "{{ source_dir }}/libtheora-1.1.1.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/libtheora-1.1.1.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true

- name: Download file and force basic auth
  get_url:
    url: https://github.com/libass/libass/releases/download/0.13.7/libass-0.13.7.tar.gz
    dest: "{{ source_dir }}/libass-0.13.7.tar.gz"
    validate_certs: no

- name: tar 
  unarchive:
    src: "{{ source_dir }}/libass-0.13.7.tar.gz"
    dest: "{{ source_dir }}"
    remote_src: true


- name: ffmpge source
  git:
    repo: 'git://source.ffmpeg.org/ffmpeg'
    dest: "{{ source_dir }}/ffmpeg/"
    update: no 

# Compiling

- name: compile nasm
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/nasm-2.13.01/"
    creates: "{{ bin_dir }}/nasm/"
  with_items:
    - ./configure  --enable-static --bindir={{ bin_dir }}
    - make -j
    - make install

- name: compile yasm
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/yasm/"
    creates: "{{ bin_dir }}/yasm/"
  with_items:
    - ./autogen.sh
    - ./configure --bindir={{ bin_dir }}
    - make -j
    - make install


- name: compile x264
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/x264/"
    creates: "{{ bin_dir }}/x264/"
  with_items:
    - ./configure --enable-static --enable-pic --disable-asm
    - make -j
    - make install


- name: compile libfdk_aac
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/fdk-aac/"
    creates: "{{ lib_dir }}/fdk_aac/"
  with_items:
    - ./autogen.sh
    - ./configure --disable-shared --with-pic
    - make -j
    - make install

- name: compile lame-3.99.5
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/lame-3.99.5/"
    creates: "{{ lib_dir }}/lame/"
  with_items:
    - ./configure --disable-shared --enable-nasm --with-pic
    - make -j
    - make install

- name: compile opus
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/opus/"
    creates: "{{ lib_dir }}/opus/"
  with_items:
    - autoreconf -fiv
    - ./configure --disable-shared --with-pic
    - make -j
    - make install

- name: compile libogg
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/libogg-1.3.2/"
    creates: "{{ lib_dir }}/libogg/"
  with_items:
    - ./configure --disable-shared --with-pic
    - make -j
    - make install

- name: compile libvorbis
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/libvorbis-1.3.4/"
    creates: "{{ lib_dir }}/libvorbis/"
  with_items:
    - ./configure --with-ogg --disable-shared --with-pic
    - make -j
    - make install

- name: compile libvpx
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/libvpx/"
    creates: "{{ lib_dir }}/libvpx/"
  with_items:
    - ./configure  --disable-shared --as=yasm --disable-unit-tests
    - make -j
    - make install

- name: compile libtheora
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/libtheora-1.1.1/"
    creates: "{{ lib_dir }}/libtheora/"
  with_items:
    - ./configure  --disable-shared --with-ogg
    - make -j
    - make install

- name: compile libtheora
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/libass-0.13.7/"
    creates: "{{ lib_dir }}/libass/"
  with_items:
    - ./configure  --disable-shared
    - make -j
    - make install


- name: compile ffmpeg
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/ffmpeg/"
    creates: "{{ bin_dir }}/ffmpeg/"
  with_items:
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --bindir={{ bin_dir }} --extra-libs=-ldl --enable-gpl --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree
    - make
    - make install

